# Generated by Django 5.2.5 on 2025-08-12 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.CharField(blank=True, max_length=3)),
                ('title', models.CharField(max_length=100)),
                ('hometown', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
